### ISSUE TITLE
don't load with varnish 4.1.0-tp1

### ISSUE THREAD

**Issue by laurentl92** [varnish/libvmod-cookie#37]
hello,

module failed to load with varnish 4.1.0-tp1 on debian wheezy amd64.

webcache24:/etc/varnish# service varnish start
[FAIL] Starting HTTP accelerator: varnishd failed!
Error:
Message from VCC-compiler:
Could not load VMOD cookie
	File name: /usr/lib/varnish/vmods/libvmod_cookie.so
	dlerror:: /usr/lib/varnish/vmods/libvmod_cookie.so: undefined symbol: VSB_trim
('input' Line 6 Pos 8)
import cookie;
-------######-

Running VCC-compiler failed, exited with 2
VCL compilation failed

**Comment by fgsch** [comment]
@laurentl92 I will talk to Lasse to get this fixed here. In the meantime I've created a master branch on my fork that include 2 changes for varnish-master. 
Please see https://github.com/fgsch/libvmod-cookie/tree/master.

**Comment by laurentl92** [comment]
perfect thanks a lot !

**Comment by fgsch** [comment]
Not sure what you want me to do with this @daghf .

I created https://github.com/varnish/libvmod-cookie/pull/38 to address this but was never committed.

**Comment by daghf** [comment]
@fgsch the repo has now been moved here, so please feel free to commit the relevant fixes and resolve this issue.

**Comment by fgsch** [comment]
Actually I believe this was addressed in 14dc7df13388c26c46da9cdf6138400a753b4dd0.
